export const DEFAULT_SKILLS = [
  { name: 'Python', category: 'Language' },
  { name: 'TypeScript', category: 'Language' },
  { name: 'JavaScript', category: 'Language' },
  { name: 'Go', category: 'Language' },
  { name: 'Java', category: 'Language' },
  { name: 'SQL', category: 'Language' },
  { name: 'React', category: 'Frontend' },
  { name: 'Next.js', category: 'Frontend' },
  { name: 'Vue', category: 'Frontend' },
  { name: 'Tailwind CSS', category: 'Frontend' },
  { name: 'Node.js', category: 'Backend' },
  { name: 'FastAPI', category: 'Backend' },
  { name: 'Django', category: 'Backend' },
  { name: 'Spring Boot', category: 'Backend' },
  { name: 'PostgreSQL', category: 'Data' },
  { name: 'MongoDB', category: 'Data' },
  { name: 'Snowflake', category: 'Data' },
  { name: 'dbt', category: 'Data' },
  { name: 'Airflow', category: 'Data' },
  { name: 'Spark', category: 'Data' },
  { name: 'AWS', category: 'Cloud' },
  { name: 'GCP', category: 'Cloud' },
  { name: 'Azure', category: 'Cloud' },
  { name: 'Docker', category: 'DevOps' },
  { name: 'Kubernetes', category: 'DevOps' },
  { name: 'Terraform', category: 'DevOps' },
  { name: 'CI/CD', category: 'DevOps' },
  { name: 'LLM Integration', category: 'AI' },
  { name: 'RAG', category: 'AI' },
  { name: 'PyTorch', category: 'AI' },
  { name: 'Machine Learning', category: 'AI' },
  { name: 'Agile / Scrum', category: 'Methodology' },
  { name: 'Technical Writing', category: 'Soft Skills' },
  { name: 'Client Communication', category: 'Soft Skills' },
];
