import { prisma } from '../db/prisma.js';
import { decryptSecret } from '../utils/crypto.js';
import { BadRequestError } from '../utils/errors.js';

// Proactive app install via Microsoft Graph: installs the databob Teams app for
// every SSO user so nobody has to add it or message the bot. Needs, on the bot's
// app registration (with admin consent): TeamsAppInstallation.ReadWriteForUser.All
// and AppCatalog.Read.All.
const GRAPH = 'https://graph.microsoft.com/v1.0';

type Conn = { appType: string; botAppId: string | null; botAppPassword: string | null; tenantId: string | null };

/** App-only Graph token via client credentials (the bot's secret). */
async function getGraphToken(c: Conn): Promise<string> {
  if (c.appType === 'UserAssignedMSI') {
    throw new BadRequestError('A managed-identity bot can only call Graph from inside Azure — use a client-secret bot for auto-install.');
  }
  const secret = c.botAppPassword ? decryptSecret(c.botAppPassword) : null;
  if (!c.botAppId || !secret) throw new BadRequestError('The Teams bot connection is not fully configured.');
  if (!c.tenantId) throw new BadRequestError('Add the tenant (directory) ID to enable auto-install.');

  const body = new URLSearchParams({
    grant_type: 'client_credentials',
    client_id: c.botAppId,
    client_secret: secret,
    scope: 'https://graph.microsoft.com/.default',
  });
  const res = await fetch(`https://login.microsoftonline.com/${encodeURIComponent(c.tenantId)}/oauth2/v2.0/token`, {
    method: 'POST',
    headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
    body,
  });
  if (!res.ok) {
    const d = await res.text().catch(() => '');
    throw new BadRequestError(`Could not get a Microsoft Graph token. ${d.slice(0, 180)}`);
  }
  const j = (await res.json()) as { access_token?: string };
  if (!j.access_token) throw new BadRequestError('Microsoft did not return a Graph token.');
  return j.access_token;
}

/** The app's catalog id (needed to install it). */
async function findCatalogAppId(token: string, botAppId: string): Promise<string> {
  const query = async (filter: string): Promise<string | undefined> => {
    const url = `${GRAPH}/appCatalogs/teamsApps?$filter=${encodeURIComponent(filter)}`;
    const res = await fetch(url, { headers: { Authorization: `Bearer ${token}` } });
    if (!res.ok) {
      const d = await res.text().catch(() => '');
      throw new BadRequestError(
        `Could not read the Teams app catalog (the bot app likely needs the AppCatalog.Read.All permission with admin consent). ${d.slice(0, 160)}`
      );
    }
    const j = (await res.json()) as { value?: Array<{ id: string }> };
    return j.value?.[0]?.id;
  };
  const esc = botAppId.replace(/'/g, "''");
  // Primary: the app whose manifest id == the bot App ID (our setup guide). Fallback:
  // an org-uploaded app named "databob" — covers a manifest id that differs from the
  // bot App ID (e.g. one generated by the Teams Developer Portal).
  const id = (await query(`externalId eq '${esc}'`)) || (await query(`displayName eq 'databob'`));
  if (!id) {
    throw new BadRequestError(
      'The databob app is not in your org app catalog yet — upload it in the Teams admin center first (and set the manifest id to your bot App ID).'
    );
  }
  return id;
}

/** Install the app for one user (by Entra object id). Idempotent: 409 = already
 *  installed. Returns the installation id when the POST created it (201). */
async function installForUser(
  token: string,
  catalogAppId: string,
  aadUserId: string
): Promise<{ status: 'installed' | 'already'; installId: string | null }> {
  const res = await fetch(`${GRAPH}/users/${encodeURIComponent(aadUserId)}/teamwork/installedApps`, {
    method: 'POST',
    headers: { Authorization: `Bearer ${token}`, 'Content-Type': 'application/json' },
    body: JSON.stringify({ 'teamsApp@odata.bind': `${GRAPH}/appCatalogs/teamsApps/${catalogAppId}` }),
  });
  if (res.status === 201) {
    const j = (await res.json().catch(() => ({}))) as { id?: string };
    return { status: 'installed', installId: j.id ?? null };
  }
  if (res.status === 409) return { status: 'already', installId: null };
  const d = await res.text().catch(() => '');
  throw new Error(`HTTP ${res.status} ${d.slice(0, 120)}`);
}

/** The teamsAppInstallation id for this user + app (needed to open the chat). */
async function findInstallationId(
  token: string,
  aadUserId: string,
  catalogAppId: string,
  botAppId: string
): Promise<string | null> {
  const url = `${GRAPH}/users/${encodeURIComponent(aadUserId)}/teamwork/installedApps?$expand=teamsApp`;
  const res = await fetch(url, { headers: { Authorization: `Bearer ${token}` } });
  if (!res.ok) return null;
  const j = (await res.json().catch(() => ({}))) as {
    value?: Array<{ id: string; teamsApp?: { id?: string; externalId?: string } }>;
  };
  const match = j.value?.find((a) => a.teamsApp?.id === catalogAppId || a.teamsApp?.externalId === botAppId);
  return match?.id ?? null;
}

/**
 * Open the 1:1 chat between the user and the app. This creates the chat thread if
 * it doesn't exist yet — which is what makes the bot receive its install event
 * (captured by teamsTransport) and surfaces the chat in the user's Teams. Merely
 * installing the app does neither. Returns an error string on failure, else null.
 */
async function openChat(token: string, aadUserId: string, installationId: string): Promise<string | null> {
  const res = await fetch(
    `${GRAPH}/users/${encodeURIComponent(aadUserId)}/teamwork/installedApps/${installationId}/chat`,
    { headers: { Authorization: `Bearer ${token}` } }
  );
  if (res.ok) return null;
  const d = await res.text().catch(() => '');
  return `chat HTTP ${res.status} ${d.slice(0, 100)}`;
}

/**
 * Install the app for every org member with a Microsoft-linked account, then open
 * each person's chat so the bot receives its install event and registers the
 * conversation (see teamsTransport.captureConversation) — so DMs work afterwards.
 */
export async function installForAllUsers(orgId: string) {
  const conn = await prisma.teamsConnection.findUnique({ where: { orgId } });
  if (!conn?.botAppId) throw new BadRequestError('Set up the Teams bot connection first.');
  const token = await getGraphToken(conn);
  const catalogAppId = await findCatalogAppId(token, conn.botAppId);

  const members = await prisma.orgMember.findMany({
    where: { orgId },
    include: { user: { select: { microsoftId: true } } },
  });
  // Only Microsoft-linked accounts can be installed for AND later matched.
  const targets = members
    .map((m) => m.user?.microsoftId)
    .filter((id): id is string => !!id);
  const skippedNoMicrosoft = members.length - targets.length;

  let installed = 0;
  let alreadyConnected = 0;
  let failed = 0;
  const errors: string[] = [];
  for (const aadId of targets) {
    try {
      const r = await installForUser(token, catalogAppId, aadId);
      // Opening the chat (for a new OR already-installed app) is what registers
      // the conversation with the bot; installing alone does not.
      const installId = r.installId ?? (await findInstallationId(token, aadId, catalogAppId, conn.botAppId));
      if (installId) {
        const chatErr = await openChat(token, aadId, installId);
        if (chatErr && errors.length < 3) errors.push(chatErr);
      }
      if (r.status === 'installed') installed++;
      else alreadyConnected++;
    } catch (e) {
      failed++;
      if (errors.length < 3) errors.push((e as Error).message);
    }
  }
  return { total: targets.length, installed, alreadyConnected, failed, skippedNoMicrosoft, errors };
}
